### ISSUE TITLE
Markbot Screenshot Issue

### ISSUE THREAD

**Issue by emahadzimustafic** [emahadzimustafic/stylish-beets#1]
Hi! Markbot says that the screenshot of my website is too visually different. This might be because I'm on a PC and not a Mac. Is there anything I have to change to fix this?

@carolsinc @hellachella

**Comment by carolsinc** [comment]
If you look at a line like "55 to 65 days..." on yours breaks to a new line, so you know it's too big. That pushes everything below it off its mark
